### ISSUE TITLE
The actual name of the resource type should be used in the log instead of "employee" and "employer"

### ISSUE THREAD

**Issue by lhanjian** [KusionStack/resourceconsist#27]
## Feature Request

**Is your feature request related to a problem? Please describe:**

no

**Describe the feature you'd like:**

The actual name of the resource type should be used in the log instead of employee and employer

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by WeichengWang1** [comment]
well received :)

**Comment by WeichengWang1** [comment]
Hi @lhanjian , 
"employer" and "employee" in the log message is not the meaning of a resource in most cases. 
For example,  "get current employer failed" is actually get current IEmployer(abstracted from the real resource) failed,
```Go
	currentEmployer, err := r.adapter.GetCurrentEmployer(ctx, employer)
	if err != nil {
		r.logger.Error(err, "get current employer failed")
		r.recorder.Eventf(employer, corev1.EventTypeWarning, "GetCurrentEmployerFailed",
			"get current employer status failed: %s", err.Error())
		return reconcile.Result{}, err
	}
```
But this issue hint me that we do need log out what the real resource is since it would be confusing which "employer" is under reconciling, and we will refactor the logs. 
Appreciate for opening the issue. 😄
