### ISSUE TITLE
controller-runtime use old version, need upgrade

### ISSUE THREAD

**Issue by lhanjian** [KusionStack/resourceconsist#39]
## Enhancement

sigs.k8s.io/controller-runtime => sigs.k8s.io/controller-runtime v0.10.3

controller-runtime API has changed,can we upgrade to 0.16.3?

**Comment by WeichengWang1** [comment]
@shaofan-hs can we upgrade controller-runtime for all kusionstack/operating related projects?

**Comment by WeichengWang1** [comment]
since kusionstack/operating uses controller-runtime v0.10.3 to suit kubernetes 1.22, we won't upgrade controller-runtime directly. Alternatively, we created branch cr-v0.15.0+ & cr-v0.18.0+ for controller-runtime v0.15.0+ & v0.18.0+. BTW, multicluter options disabled temporarily in these 2 branches since kusionstack.io/kube-utils/multicluster adopted controller-runtime v0.10.3 too.
